# docker run -it --rm -v $PWD:/app -w /app elixir
# docker-compose run --rm iex
# docker-compose up

version: '3'

services:
  iex:
    # build: .
    image: elixir
    # command: bash -c "iex"
    # command: iex
    tty: true
    stdin_open: true
    # なんかうまくいかん
    working_dir: /app
    volumes:
      - .:/app
